### ISSUE TITLE
Translating DOM to SVG adds IDs to html elements

### ISSUE THREAD

**Issue by festim-prebreza** [felixfbecker/dom-to-svg#103] opened 2021-03-12 15:00 UTC
While translating, the library adds some text to IDs affecting our SVG code. However, it does not update those same IDs in those fill=url(#ID) properties in SVGs. This results in ID incompatibility (the fill does not find the correct ID), thus SVG does not render correctly. Can you not modify our elements IDs or just update the fill property as well?

**Comment by felixfbecker** [comment] 2021-04-17 22:22
Duplicate of #85

**Closed by felixfbecker** 2021-04-17 22:22 UTC
